;keypad read input section
;code referenced from http://www.avr-asm-tutorial.net/avr_en/apps/key_matrix/keypad/keyboard.html#io

init_keypad:
	ldi temp, 0b11110000 ; data direction register column lines output
	out DDRC, temp    ; set direction register
	ldi temp, 0b00001111 ; Pull-Up-Resistors to lower four port pins
	out PORTC, temp    ; to output port
;
; Check any key pressed
;
read_key:
	ldi temp, 0b00001111 ; PB4..PB6=Null, pull-Up-resistors to input lines
	out PORTC, temp    ; of port pins PB0..PB3
	in temp, PINC    ; read key results
	ori temp,0b11110000 ; mask all upper bits with a one
	cpi temp,0b11111111 ; all bits = One?
	breq read_key        ; yes, no key is pressed

;
; Identify the key pressed
;
ReadKey:
	ldi ZH,HIGH(2*KeyTable) ; Z is pointer to key code table
	ldi ZL,LOW(2*KeyTable)

	; read column 4
	ldi temp, 0b01111111 ; PB7 = 0
	out PORTC, temp
	in temp, PINC ; read input line
	ori temp, 0b11110000 ; mask upper bits
	cpi temp, 0b11111111 ; a key in this column pressed?
	brne KeyRowFound ; key found
	adiw ZL,4 ; column not found, point Z one row down

	; read column 3
	ldi temp, 0b10111111 ; PB6 = 0
	out PORTC, temp
	in temp, PINC ; read input line
	ori temp, 0b11110000 ; mask upper bits
	cpi temp, 0b11111111 ; a key in this column pressed?
	brne KeyRowFound ; key found
	adiw ZL,4 ; column not found, point Z one row down

	; read column 2
	ldi temp, 0b11011111 ; PB5 = 0
	out PORTC, temp
	in temp, PINC ; read again input line
	ori temp, 0b11110000 ; mask upper bits
	cpi temp, 0b11111111 ; a key in this column?
	brne KeyRowFound ; column found
	adiw ZL,4 ; column not found, another four keys down

	; read column 1
	ldi temp, 0b11101111 ; PB4 = 0
	out PORTC, temp
	in temp, PINC ; read again input line
	ori temp, 0b11110000 ; mask upper bits
	cpi temp, 0b11111111 ; a key in this column?
	brne KeyRowFound ;column found

	breq read_key ; unexpected: no key in this column pressed

KeyRowFound: ; column identified, now identify row
	lsr temp ; shift a logic 0 in left, bit 0 to carry
	brcc KeyProc ; a zero rolled out, key is found

	adiw ZL,1 ; point to next key code of that column
	rjmp KeyRowFound ; repeat shift

;process keyinput
KeyProc:
	lpm 
	mov key, r0
	cpi key, 0xF0
	breq init_keypad
	rcall DELAY_01
	rjmp DONE

	
	cpi key , 1
	breq ONE
	cpi key, 2
	breq TWO
	cpi key, 3
	breq THREE
	cpi key, 4
	breq FOUR
	cpi key, 5
	breq FIVE
	cpi key, 6
	breq SIX
	cpi key, 7
	breq SEVEN
	cpi key, 8
	breq EIGHT
	cpi key, 9
	breq NINE


ZERO:
	ldi temp, 0x00
	out PORTE, temp
	rjmp DONE

ONE:
	ldi temp, 0x01
	out PORTE, temp
	rjmp DONE

TWO:
	ldi temp, 0x02
	out PORTE, temp
	rjmp DONE

THREE:
	ldi temp, 0x03
	out PORTE, temp
	rjmp DONE

FOUR:
	ldi temp, 0x04
	out PORTE, temp
	rjmp DONE

FIVE:
	ldi temp, 0x05
	out PORTE, temp
	rjmp DONE

SIX:
	ldi temp, 0x06
	out PORTE, temp
	rjmp DONE

SEVEN:
	ldi temp, 0x07
	out PORTE, temp
	rjmp DONE

EIGHT:
	ldi temp, 0x08
	out PORTE, temp
	rjmp DONE

NINE:
	ldi temp, 0x09
	out PORTE, temp
	rjmp DONE

	
DELAY_01:
	; Generated by delay loop calculator
	; at http://www.bretmulvey.com/avrdelay.html
	;
	; DELAY_CONTROL 40 000 cycles
	; 5ms at 8.0 MHz

	    ldi  temp, 52
	    ldi  temp4, 242
	L1: dec  temp4
	    brne L1
	    dec  temp
	    brne L1
	    nop
	ret

DONE :
